version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    command: /opt/mssql/bin/sqlservr
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password1234!"
    stdin_open: true
    ports:
      - 1433:1433
    networks:
      - db_net
  sqlcmd:
    image: mcr.microsoft.com/mssql-tools:latest
    command: /opt/mssql_scripts/initialize-db.sh
    platform: linux/arm64
    stdin_open: true
    volumes:
      - ./db-scripts:/opt/mssql_scripts
    networks:
      - db_net
networks:
  db_net:
    name: db_net