version: '3.8'
services:
  # web:
  #   container_name: nextjs_container
  #   build: .
  #   command: tail -f /dev/null
  #   ports:
  #    - 3000:3000
  #   depends_on:
  #     - sql-server-db
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1234!"
      ACCEPT_EULA: "Y"
      DB_NAME: "CompetitiveStanding"
    volumes:
      - db-data:/var/opt/mssql/data
volumes:
  db-data:
