version: '3.8'
services:
  # web:
  #   container_name: nextjs_container
  #   build: .
  #   command: tail -f /dev/null
  #   ports:
  #    - 3000:3000
  #   depends_on:
  #     - sql-server-db
  sql-server-db:
    container_name: sql-server-db
    build: ./db-scripts/
    ports:
      - "1433:1433"
#     volumes:
#       - db-data:/var/opt/mssql/data
# volumes:
#   db-data:
