/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** Type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export type paths = {
  "/users": {
    /** Create a new user */
    post: operations["createUser"];
  };
  "/users/{memorableId}": {
    /** Get user by memorable id */
    get: operations["getUserByMemorableId"];
  };
  "/locations": {
    /** Get all locations */
    get: operations["getAllLocations"];
  };
  "/locations/{locationId}": {
    /** Get location by id */
    get: operations["getLocationById"];
  };
};

export type components = {
  schemas: {
    User: {
      /** @example 1 */
      id: number;
      /** @example abc */
      memorableId: string;
      /** @example John */
      firstName: string;
      /** @example James */
      lastName: string;
      /** @example London */
      location?: string;
      /** @example https://i.pinimg.com/736x/f1/0f/f7/f10ff70a7155e5ab666bcdd1b45b726d.jpg */
      profilePicture?: string;
    };
    GameType: {
      /** @example 1 */
      id: number;
      /** @example Pool */
      name: string;
      /** @example 1 */
      maxNumberOfPlayers: number;
    };
    Location: {
      /** @example 1 */
      id: number;
      /** @example Nottingham */
      name: string;
      /** @example https://www.thetrainline.com/content/vul/hero-images/city/nottingham/1x.jpg */
      coverPhoto?: string;
      availableGames?: (components["schemas"]["GameType"])[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};

export type external = Record<string, never>;

export type operations = {

  createUser: {
    /** Create a new user */
    requestBody: {
      content: {
        "application/json": {
          /** @example abc */
          memorableId: string;
          /** @example John */
          firstName: string;
          /** @example James */
          lastName: string;
          /** @example https://i.pinimg.com/736x/f1/0f/f7/f10ff70a7155e5ab666bcdd1b45b726d.jpg */
          profilePictureUrl?: string;
          /** @example 1 */
          homeLocationId?: number;
        };
      };
    };
    responses: {
      /** @description successful operation */
      201: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  getUserByMemorableId: {
    /** Get user by memorable id */
    parameters: {
        /** @example 4e8 */
      path: {
        memorableId: string;
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description User not found */
      404: never;
    };
  };
  getAllLocations: {
    /** Get all locations */
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/json": (components["schemas"]["Location"])[];
        };
      };
    };
  };
  getLocationById: {
    /** Get location by id */
    parameters: {
      path: {
        locationId: number;
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["Location"];
        };
      };
    };
  };
};
